### PR TITLE
The main content has arrived

### PR DESCRIPTION
**Pull request by thomaseichhorn**
The performance chapter from my thesis. Some references might be out, I'll add them later. Pictures are in eps and pdf. Removed pdf from gitignore for this. Some text editing will be needed...

### CODE REVIEW

**Comment by simonspa** [comment]
you don't have to remove `pdf` from `.gitignore` to add files - just use

```
git add -f file.pdf
```

**Comment by thomaseichhorn** [comment]
that's how I added them, but thats like 3 keystrokes extra :)

**Comment by TCThenna** [comment]
I tried to compile. All your includegraphics have gfk/chapter3/.../ paths from your thesis environment in. Please change to figures/

**Comment by thomaseichhorn** [comment]
I posted a full quote... not only will the pictures not work, also some references are not in. But since the text dump needs some adjustmenst for this paper anyway, this can be done during editing.

**Pull request merged**
